### ISSUE TITLE
"Try Kong" instructions not working

### ISSUE THREAD

**Issue by minusdavid** [Kong/kong-vagrant#102]
I've tried https://docs.konghq.com/install/vagrant/ and compared with the "Try Kong" instructions from https://github.com/Kong/kong-vagrant#try-kong and this process doesn't work at all (at least with a Windows host). 

It seems that Cassandra, Postgres, and Redis are running, but there's nothing listening on ports 8000, 8002, 8443, 8444:

vagrant@ubuntu-xenial:~$ sudo netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1265/sshd
tcp        0      0 127.0.0.1:7000          0.0.0.0:*               LISTEN      2458/java
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      1502/postgres
tcp        0      0 127.0.0.1:34492         0.0.0.0:*               LISTEN      2458/java
tcp        0      0 127.0.0.1:7199          0.0.0.0:*               LISTEN      2458/java
tcp6       0      0 127.0.0.1:9042          :::*                    LISTEN      2458/java
tcp6       0      0 :::22                   :::*                    LISTEN      1265/sshd
tcp6       0      0 :::5432                 :::*                    LISTEN      1502/postgres

**Comment by minusdavid** [comment]
I tried things from https://docs.konghq.com/0.14.x/getting-started/quickstart/ but nothing works there either.

**Comment by minusdavid** [comment]
Looks like maybe this is my problem: https://github.com/openresty/docker-openresty/issues/39

**Comment by minusdavid** [comment]
I'm closing this issue after reading https://github.com/Kong/kong/issues/2846, but you folk should really include a warning about older CPUs not being able to run OpenResty/Kong.

**Comment by p0pr0ck5** [comment]
Hi @minusdavid, thanks for noting your results here. Do note that our docs are open source available here:https://github.com/Kong/docs.konghq.com ; we’d be happy to receive a contribution in this regard. Thanks!

**Comment by minusdavid** [comment]
Cool. Will be sending a pull request shortly. Thanks for the info!
