### ISSUE TITLE
no file at: /etc/kong/kong.conf

### ISSUE THREAD

**Issue by numediaweb** [Kong/kong-vagrant#109]
I just installed Kong and set the forwarding ports to as:
```
  config.vm.network :forwarded_port, guest: 8000, host: 8010
  config.vm.network :forwarded_port, guest: 8001, host: 8011
  config.vm.network :forwarded_port, guest: 8443, host: 8443
  config.vm.network :forwarded_port, guest: 8444, host: 8444
  config.vm.network :forwarded_port, guest: 9000, host: 9000 # only used with TCP stream proxy with Kong >= 0.15.0
  config.vm.network :forwarded_port, guest: 5432, host: 65432
```

When I ssh to the machine and do: `kong check`

I get:

```
 [error] no file at: /etc/kong/kong.conf
```

**Comment by Tieske** [comment]
confirmed! but it should just work. Doesn't it?

**Comment by Tieske** [comment]
see https://docs.konghq.com/1.0.x/cli/#kong-check

it checks the validity of the conf file. It errors if you do not provide a conf file. But without a conf file, Kong will start using defaults anyway

**Comment by Tieske** [comment]
@numediaweb ping?

**Comment by numediaweb** [comment]
@Tieske Yes Kong works but still, I think it would be great to get rid of the error.
Thanks

**Comment by Tieske** [comment]
The configuration file command line parameter is not optional, it is required. So based on the way you are invoking it the error is valid. It defaults to `/etc/kong/kong.conf`, but then still that file should be present, which it isn't, hence the error.

Why would you expect otherwise?

**Comment by Tieske** [comment]
closing this.
