### ISSUE TITLE
Package 'oracle-java8-installer' has no installation candidate

### ISSUE THREAD

**Issue by RedDragonet** [Kong/kong-vagrant#116]
> https://launchpad.net/~webupd8team/+archive/ubuntu/java

The Oracle JDK License has changed for releases starting April 16, 2019.

The new Oracle Technology Network License Agreement for Oracle Java SE is substantially different from prior Oracle JDK licenses. The new license permits certain uses, such as personal use and development use, at no cost -- but other uses authorized under prior Oracle JDK licenses may no longer be available. Please review the terms carefully before downloading and using this product. An FAQ is available here: https://www.oracle.com/technetwork/j...-jdk-faqs.html

Oracle Java downloads now require logging in to an Oracle account to download Java updates, like the latest Oracle Java 8u211 / Java SE 8u212. Because of this I cannot update the PPA with the latest Java (and the old links were broken by Oracle).

For this reason, THIS PPA IS DISCONTINUED

**Comment by Tieske** [comment]
sorry, what is the issue about? What action do you expect to be taken?

**Comment by RedDragonet** [comment]
RUN `vagrant up` command, get an error `Package 'oracle-java8-installer' has no installation candidate`.
The relevant code is here  https://github.com/Kong/kong-vagrant/blob/master/provision.sh#L184

**Comment by RedDragonet** [comment]
Postgresql is also not installed correctly, get an error `Package 'postgresql-9.6' has no installation candidate`. 
Finally, the kong service could not be started properly.

**Comment by Tieske** [comment]
I cannot reproduce this. It works for me?

**Comment by RedDragonet** [comment]
Thanks @Tieske , I used the network proxy to run successfully.

**Comment by RedDragonet** [comment]
[official website](https://docs.konghq.com/install/vagrant/) step 2 of installation is confusing .
```sh
# specify migrations flag to initialise the datastore
$ vagrant ssh -c "kong start --run-migrations"
```

AND README is
```sh
$ kong migrations bootstrap
# if you are running Kong < 0.15.0, run this instead:
# $ kong start --run-migrations
$ kong start
```
The installation steps using the official website are inaccurate.

**Comment by Tieske** [comment]
yes, I just verified, those instructions are outdated. Issue created https://github.com/Kong/docs.konghq.com/issues/1246

Yet I cannot verify the oracle java installer error you're getting. Could it be related to using a proxy as you mentioned: "I used the network proxy to run successfully"?

I do not have a proxy, so cannot confirm.

**Comment by RedDragonet** [comment]
Thank you very much @Tieske
