### ISSUE TITLE
reuseport: command not found

### ISSUE THREAD

**Issue by nmundar** [Kong/kong-vagrant#134]
I'm having trouble running provisioning script. It breaks on setup of KONG_ADMIN_LISTEN var that was recently reworked. 

`default: /tmp/vagrant-shell: line 73: reuseport: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

The problem is that new command was not put into quotes. When in quotes provisioning passes without errors.

**Comment by nmundar** [comment]
I've made a PR with the fix:
https://github.com/Kong/kong-vagrant/pull/135

**Comment by Tieske** [comment]
mind sending a PR?

**Comment by Tieske** [comment]
ah, there you go.

Thks 😄
