### ISSUE TITLE
`kong migrations bootstrap` fails with `Error: proxy_listen must be of form:...`

### ISSUE THREAD

**Issue by kikito** [Kong/kong-vagrant#138]
Steps to reproduce:
1. git pull
2. `vagrant up`
3. `vagrant ssh`
4. `kong migrations bootstrap`

The complete error is:
```
Error: proxy_listen must be of form: [off] | <ip>:<port> [ssl] [http2] [proxy_protocol] [deferred] [bind] [reuseport] [backlog=%d+], [... next entry ...]
```

I believe that the problem is the `transparent` part of the proxy_protocol, introduced by provision.sh here:
```
if [ $KONG_NUM_VERSION -ge 001500 ]; then
  # use Bionic now instead of Trusty
  KONG_DOWNLOAD_URL="https://bintray.com/kong/kong-deb/download_file?file_path=kong-${KONG_VERSION}.bionic.all.deb"

  # Let's enable transparent listening option as well
  KONG_PROXY_LISTEN="0.0.0.0:8000 transparent, 0.0.0.0:8443 transparent ssl"

  # Kong 0.15.0 has a stream module, let's enable that too
  KONG_STREAM_LISTEN="0.0.0.0:9000 transparent"
fi
```

I believe `transparent` is not valid in 2.0.x

**Comment by Tieske** [comment]
did you maybe have the vagarnt box still around? did you destroy it before doing `vagrant up`?

This problem was fixed 2 weeks ago; see https://github.com/Kong/kong-vagrant/pull/133

**Comment by kikito** [comment]
I confirm that the problem was on my setup. Somehow the `git up` command didn't update to the latest version of `kong-vagrant`. After running the same steps I described in the issue again, it went smoothly.
