### ISSUE TITLE
dev does not correspond to KONG_VERSION

### ISSUE THREAD

**Issue by msummers-nr** [Kong/kong-vagrant#141]
I created my vagrant with KONG_VERSION=1.1.2. Kong version 1.1.2 installs but when I cd to `/kong` the Kong rockspec is 2.0.2 and in the Makefile the DEV_ROCKS look like they're for 2.x:

`DEV_ROCKS = "busted 2.0.0" "busted-htest 1.0.0" "luacheck 0.23.0" "lua-llthreads2 0.1.5" "http 0.3"`

Removing  `kong-2.0.2-0.rockspec`  and adding `kong-1.1..2-0.rockspec` from the Kong repo didn't help, make fails.

Any suggestions on how to create dev for a back-version of Kong?

**Comment by hishamhm** [comment]
@msummers-nr For going to a past _major_ version like 1.1.2, I would recommend going [back in the Git history](https://github.com/Kong/kong-vagrant/commits/master) of this repo.

```
git checkout 86760522f44c0a1f45d1e7719ee5d54be995f657
```

This should give you a 1.1.2-compatible setup.

Alternatively, you might want to take a look at [Pongo](https://github.com/kong/kong-pongo).

**Comment by Tieske** [comment]
@msummers-nr make sure that you check out your Git source kong of the Kong repo to the same version. The source tree inside the vagrant box at `/kong` is a mount to your host system. So make sure that repo is checked out to the same version as the binaries installed when you build the vagrant box.

**Comment by Tieske** [comment]
As @hishamhm mentioned you can also use Pongo, if all you want is develop a plugin. That would be the easier way. If developing on Kong itself, use the vagrant box.

**Comment by Tieske** [comment]
@msummers-nr was this resolved? can we close it?
