### ISSUE TITLE
KONG_VERSION 1.4.3 installation does not work due missing deb package

### ISSUE THREAD

**Issue by hrodic** [Kong/kong-vagrant#163]
As per documentation, to use different versions with: 
`KONG_VERSION=1.4.3 vagrant up --provision`

Using 1.4.2 works because this package exists
https://bintray.com/kong/kong-deb/download_file?file_path=kong-1.4.2.bionic.amd64.deb

With this correct message

> default: Fetching and installing Kong 1.4.2
    default: *************************************************************************
    default: https://bintray.com/kong/kong-deb/download_file?file_path=kong-1.4.2.bionic.amd64.deb
    default: 
    default: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    default: Reading package lists...
    default: Building dependency tree...
    default: 
    default: Reading state information...
    default: The following NEW packages will be installed:
    default:   kong
    default: 0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
    default: Need to get 0 B/29.5 MB of archives.
    default: After this operation, 91.0 MB of additional disk space will be used.
    default: Get:1 /home/vagrant/kong.deb kong amd64 1.4.2 [29.5 MB]

Using 1.4.3 fails because this package does not exists (but the 1.4.3 patch is important due security fixes)
https://bintray.com/kong/kong-deb/download_file?file_path=kong-1.4.3.bionic.amd64.deb

Giving the followiging error with vagrant

> default: *************************************************************************
    default: Fetching and installing Kong 1.4.3
    default: *************************************************************************
    default: https://bintray.com/kong/kong-deb/download_file?file_path=kong-1.4.3.bionic.amd64.deb
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Could be possible to make this package available? thank you.

**Comment by hutchic** [comment]
Curious that package isn't available. The CI build log says it was buld and successfully released and we've never had a past report that it was MIA.

Regardless I built / released it for you :+1:

**Comment by hrodic** [comment]
thanks for the help!
