### ISSUE TITLE
I can not load my custom plugins on Windows platform

### ISSUE THREAD

**Issue by zjf0535** [Kong/kong-vagrant#176]
I installed kong-vagrant  according to the following steps in order to create a ennvironment  to develop kong plugin but my plugings never were loaded. What should I do ?

**Comment by Tieske** [comment]
Can you be more specific, which steps, what was the result, and what was unexpected

**Comment by Tieske** [comment]
btw; for plugin development you might also want to have a look at Pongo. https://github.com/Kong/kong-pongo

**Comment by Tieske** [comment]
closing this
