### ISSUE TITLE
on plugin 'myplugin': myplugin plugin is enabled but not installed

### ISSUE THREAD

**Issue by zffocussss** [Kong/kong-vagrant#182]
Hi team:
    I am using vagrant to write customized plugins.I use the plugin [https://github.com/Kong/kong-plugin](url) to play . but when kong start. it failed as "on plugin 'myplugin': myplugin plugin is enabled but not installed;"

2021/09/07 08:54:56 [verbose] stopped services
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:75: /usr/local/share/lua/5.1/kong/cmd/start.lua:64: nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:514: error loading plugin schemas: on plugin 'myplugin': myplugin plugin is enabled but not installed;
no plugin found
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:514: in function 'init'
	init_by_lua:3: in main chunk

stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:75: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
	[C]: in function 'xpcall'

**Comment by Tieske** [comment]
@zffocussss I would strongly suggest to use Pongo instead, see https://github.com/Kong/kong-pongo (Vagrant is a generic dev env for Kong, where Pongo is optimized for plugins)

**Comment by Tieske** [comment]
any updates? or can we close this?
