### ISSUE TITLE
kong-vagrant tag policy and bintray sunset effect on older tags.

### ISSUE THREAD

**Issue by hrodic** [Kong/kong-vagrant#184]
Hello.

We are using this project for developing custom plugins and to ensure that everything works fine.

Currently we still have to maintain a 1.4.3 version (which we are migrating to 2.5.1  this year btw).

My questions are:
* What is the policy that you follow for tagging kong-vagrant releases? since 2.1.x no more tags have been provided (could it be possible to have a tag per minor release for example? 2.5.x for example.
* Since bintray sunset  (no more bintray downloads are possible) all previous tags that provision.sh rely on bintray urls are no longer valid and not working so the project cannot be used (is it possible to fix, which is guess would be to replace the bintray urls for the new ones wherever they are located? for previous tag that are still supported by your team?)

Thanks a lot!

**Comment by Tieske** [comment]
this repo is in neglect... I would strongly advise you to switch to using Pongo for plugin testing.

**Comment by Tieske** [comment]
That said we should probably add the tags for newer releases, but updating the old ones to overcome Bintray deprecation.... I don't see that happening, unless a community PR is provided.

**Comment by hrodic** [comment]
thanks a lot of the Pongo advise, i'll check that.

Cheers.
