### ISSUE TITLE
beyond HTTP(S)_PROXY

### ISSUE THREAD

**Issue by keizo042** [Kong/kong-vagrant#75]
hello, kong project.
Thanks you for the great project.

## Problem

`provision.sh`  doesn't take care  HTTP_PROXY, HTTPS_PROXY enviroment variable.
so, `vagrant up` stop after `Installing Kong version` message inside http proxy.

## Proposal

`$6` of provison.sh accpets HTTP(S) proxy host.
and `provision.sh` configure.

**Comment by Tieske** [comment]
Would you mind sending a PR for this?

**Comment by keizo042** [comment]
Of course, not!
I'll do it over the weekend.
