### ISSUE TITLE
Silent Error

### ISSUE THREAD

**Issue by miguelramos** [Kong/kong-vagrant#85]
Just followed the steps that you have to use the vagrant file, but every time i run the kong command on terminal nothing happens.

I've made a simple test on version 0.13.0 of vagrant and same.

![image](https://user-images.githubusercontent.com/495720/38763336-38e84624-3f91-11e8-91d8-fe6925976f23.png)

Empty Response:

![image](https://user-images.githubusercontent.com/495720/38763342-4b9d5016-3f91-11e8-9387-3b819e74e57d.png)

Here you will see version xenial from ubuntu but i've tried even precise, trusty all the same with version 0.13.0.

Thanks.

**Comment by Tieske** [comment]
I have a hard time following what you're doing? Not one of those commands is in the read me?

**Comment by Tieske** [comment]
@miguelramos ping

**Comment by Tieske** [comment]
closing this due to no response
